const expo = require('eslint-config-expo/flat');

module.exports = [
  ...expo,
  {
    ignores: [
      'node_modules/',
      'dist/',
      '.expo/',
      '.gemini/',
      'supabase/',
      'src/components/__tests__/__snapshots__/',
      'src/framework/',
      'do_b64.js',
      'gen_audits.js',
      'generator.js',
      'migrate.js',
      'write_b64.js',
      'gen_b64.js',
      'gen_b64_chunks.js',
      'scratch-args.js',
      'scratch-test.js',
      'scratch-test2.js',
      'scratch-test3.js',
      'scratch-test4.js',
      'scratch-test5.js',
      'scratch.js',
      'test-ejs.js',
      'do_exec.js',
      'fix_tests.js',
      'gen_cmd.js',
      'fix_loss.js',
      'fix_loss2.js',
      'rewrite.js',
    ],
  },
  {
    files: ['**/__tests__/**/*.js', '**/*.test.js', 'src/test/jest-setup.ts'],
    languageOptions: {
      globals: {
        it: 'readonly',
        expect: 'readonly',
        jest: 'readonly',
      },
    },
  },
  {
    rules: {
      'react-hooks/set-state-in-effect': 'off',
      'react/no-unescaped-entities': 'off',
      'react-hooks/immutability': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/array-type': 'off',
      'react-hooks/exhaustive-deps': 'off',
      'import/first': 'off',
      'import/no-named-as-default': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/globals': 'off',
      'react/display-name': 'off',
      'react/no-children-prop': 'off',
    },
  },
];
