
export const semanticTypeTemplate = (name: string) => `import { GraphNode } from '../../lib/vkg/types';

/**
 * Represents a W3C RDF / Schema.org ${name} semantic entity.
 * Auto-generated by Zoe CLI Scaffold.
 */
export interface ${name} extends GraphNode {
  '@type': 'https://schema.org/${name}';
  name?: string;
  description?: string;
  identifier?: string;
  [property: string]: any;
}
`;

export const hookTemplate = (name: string) => `/**
 * Reusable React Hook to interact with Schema.org ${name} entity in the VKG.
 * Auto-generated by Zoe CLI Scaffold.
 */
import { createSemanticHook } from '../framework/data';
import { ${name} } from '../types/semantic/${name}';

export const use${name} = createSemanticHook<${name}>('https://schema.org/${name}');
`;

export const uiTemplate = (name: string) => `import React from 'react';
import { View, StyleSheet } from 'react-native';
import { StyledText } from '../framework/ui/StyledText';
import { ${name} } from '../types/semantic/${name}';

interface ${name}CardProps {
  data: ${name};
}

/**
 * Auto-generated UI component for ${name} resource.
 */
export const ${name}Card: React.FC<${name}CardProps> = ({ data }) => {
  return (
    <View style={styles.container}>
      <StyledText style={styles.title}>{data.name || 'Untitled ${name}'}</StyledText>
      <StyledText style={styles.description}>{data.description || 'No description available.'}</StyledText>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    padding: 16,
    borderRadius: 8,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginVertical: 8,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  description: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
});
`;

export const syncTemplate = (name: string) => `import { FrameworkSyncEngine } from '../engine';
import { SyncJobBase } from '../types';

/**
 * Sync handler for ${name} resources.
 * Auto-generated by Zoe CLI Scaffold.
 */
export class ${name}SyncHandler extends FrameworkSyncEngine<SyncJobBase> {
  protected supportedJobTypes = ['${name.toLowerCase()}.create', '${name.toLowerCase()}.update'];

  protected async dispatchJob(job: SyncJobBase): Promise<void> {
    console.log('[${name}SyncHandler] Dispatching job:', job);
    // Implementation for ${name} sync goes here
    return Promise.resolve();
  }
}
`;
