/**
 * @fileoverview Type definitions for Zero-Knowledge Proof (ZKP) Identity framework.
 */

/**
 * Supported comparison operators for ZKP claims.
 */
export type ZkOperator = 'GT' | 'GTE' | 'LT' | 'LTE' | 'EQ' | 'NEQ' | 'IN' | 'NIN';

/**
 * A claim that can be verified via ZKP without revealing the actual value.
 * Example: { field: 'age', operator: 'GTE', threshold: 18 }
 */
export interface ZkClaim {
  id: string;
  field: string;
  operator: ZkOperator;
  threshold: any;
  description?: string;
}

/**
 * A proof generated by a prover to satisfy a ZkClaim.
 * Contains the cryptographic proof parameters (pi_a, pi_b, pi_c).
 */
export interface ZkProof {
  claimId: string;
  proofData: string; // Base64 encoded or JSON string of the cryptographic proof
  publicSignals: string[]; // Public inputs used for verification
  enclaveSignature?: string; // Cryptographic signature from the device's Secure Enclave to prevent proof malleability
}

/**
 * Result of a ZKP verification process.
 */
export interface ZkVerificationResult {
  verified: boolean;
  claimId: string;
  timestamp: number;
  error?: string;
}

/**
 * Interface for a ZKP Provider that can verify proofs.
 */
export interface ZkProvider {
  verify(claim: ZkClaim, proof: ZkProof): Promise<ZkVerificationResult>;
}
