import { useEffect, useState, useCallback } from 'react';
import { VirtualKnowledgeGraphClient } from '../lib/vkg/client';
import { DataFactory } from '../lib/vkg/rdf';
import { Sermon } from '../types/semantic/Sermon';

const vkgClient = new VirtualKnowledgeGraphClient();

/**
 * Reusable React Hook to interact with Schema.org Sermon entity in the VKG.
 * Auto-generated by Hygen.
 */
export function useSermon(id?: string) {
  const [node, setNode] = useState<Sermon | null>(null);
  const [loading, setLoading] = useState<boolean>(!!id);
  const [error, setError] = useState<Error | null>(null);

  const fetchNode = useCallback(async () => {
    if (!id) return;
    setLoading(true);
    setError(null);
    try {
      // RDF.js match query to resolve node from local quads store
      const subject = DataFactory.namedNode(id);
      const predicateType = DataFactory.namedNode('http://www.w3.org/1999/02/22-rdf-syntax-ns#type');
      const objectType = DataFactory.namedNode('https://schema.org/Sermon');
      
      const typeQuads = await vkgClient.match(subject, predicateType, objectType);
      if (typeQuads.length === 0) {
        setNode(null);
        setLoading(false);
        return;
      }

      // Query all quads sharing this subject to build JSON-LD
      const nodeQuads = await vkgClient.match(subject);
      const [jsonLd] = vkgClient.quadsToJsonLd(nodeQuads);
      setNode((jsonLd as Sermon) || null);
    } catch (err: any) {
      setError(err);
    } finally {
      setLoading(false);
    }
  }, [id]);

  useEffect(() => {
    fetchNode();
  }, [fetchNode]);

  const mutate = useCallback(
    async (updatedData: Omit<Sermon, '@type' | '@id'>) => {
      if (!id) throw new Error('Cannot mutate node without a valid identifier.');
      const fullNode: Sermon = {
        ...updatedData,
        '@id': id,
        '@type': 'https://schema.org/Sermon',
      };

      // Convert JSON-LD to quads list and write to VKG
      const quadsList = vkgClient.jsonLdToQuads(fullNode);
      await vkgClient.addQuads(quadsList);
      setNode(fullNode);
    },
    [id]
  );

  const remove = useCallback(async () => {
    if (!id) return;
    const subject = DataFactory.namedNode(id);
    const nodeQuads = await vkgClient.match(subject);
    await vkgClient.removeQuads(nodeQuads);
    setNode(null);
  }, [id]);

  return {
    node,
    loading,
    error,
    mutate,
    remove,
    refresh: fetchNode,
  };
}
