/**
 * Reusable React Hook to interact with Schema.org Sermon entity in the VKG.
 * Auto-generated by Hygen.
 */
import { createSemanticHook } from '../framework/data';
import { Sermon } from '../types/semantic/Sermon';

export const useSermon = createSemanticHook<Sermon>('https://schema.org/Sermon');
