---
to: supabase/migrations/view_<%= name.toLowerCase() %>.sql
---
-- Virtual RDF/JSON-LD View mapping relational database tables to Schema.org <%= name %>
-- Auto-generated by Hygen.

-- CREATE OR REPLACE VIEW <%= name.toLowerCase() %>_ld AS
-- SELECT 
--   id AS "@id",
--   'https://schema.org/<%= name %>' AS "@type",
--   name AS "name",
--   description AS "description"
-- FROM your_relational_table;
