import * as fs from 'fs';
import * as path from 'path';
import { consola } from 'consola';
import { readSupabaseStatusEnv } from './supabase-context';

export async function writeTruexEnv(options: { write: boolean }) {
  const statusEnv = await readSupabaseStatusEnv();

  const url = statusEnv.API_URL || 'http://127.0.0.1:54321';
  const anonKey = statusEnv.ANON_KEY || 'missing_anon_key';
  const serviceRoleKey = statusEnv.SERVICE_ROLE_KEY || 'missing_service_role_key';

  const envContent = `# Generated by Truex CLI - DO NOT EDIT MANUALLY
# These values are pulled dynamically from local Supabase stack

EXPO_PUBLIC_SUPABASE_URL=${url}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${anonKey}

# Supabase Local Stack
TRUEX_SUPABASE_URL=${url}
TRUEX_SUPABASE_ANON_KEY=${anonKey}
TRUEX_SUPABASE_SERVICE_ROLE_KEY=${serviceRoleKey}
`.trim();

  if (options.write) {
    const projectRoot = process.cwd();
    const envPath = path.resolve(projectRoot, '.env.truex.local');
    fs.writeFileSync(envPath, envContent, 'utf8');
    consola.success(`Successfully wrote Truex environment to: .env.truex.local`);
  } else {
    consola.info('Dry run env config output:');
    console.log(envContent.replace(serviceRoleKey, '[MASKED_SERVICE_ROLE]'));
    consola.info('Run with --write flag to persist these keys:');
    consola.info('  npm run truex supa env -- --write');
  }

  // boundary rule print
  console.log(`
Runtime Boundary Verification:
  Expo:        view-only (observes EXPO_PUBLIC_*)
  CLI:         operator authority (observes TRUEX_*)
  Supabase:    execution authority (authoritative Edge Runtime)
`);
}
