import { semanticTypeTemplate, hookTemplate, uiTemplate, syncTemplate } from '../../../dx/cli-scaffold/templates';

export const compositionalCRUDTemplate = (name: string) => {
  const slug = name.toLowerCase();
  
  const semanticType = semanticTypeTemplate(name);
  const hook = hookTemplate(name);
  const ui = uiTemplate(name);
  const sync = syncTemplate(name);

  const aiSearch = `import { IntelligenceCapability } from '../../../lib/v2030/intelligence/types';
import { ${name} } from '../../../types/semantic/${name}';

/**
 * AI-powered search capability for ${name} entities.
 * Auto-generated by Zoe Compositional Blueprint.
 */
export const ${name}SearchCapability: IntelligenceCapability = {
  id: '${slug}-search',
  name: '${name} AI Search',
  description: 'Semantic search for ${name} resources using vector embeddings.',
  inputContract: {
    properties: {
      query: { type: 'string', description: 'Natural language search query', required: true }
    }
  },
  outputContract: {
    properties: {
      results: { type: 'array', description: 'Matched ${name} entities' }
    }
  },
  async run(input: { query: string }) {
    console.log('[${name}SearchCapability] Searching for:', input.query);
    // AI Search implementation logic
    return {
      success: true,
      result: { results: [] },
      logs: [\`Executed semantic search for \${input.query}\`]
    };
  }
};
`;

  const screen = `import React, { useState } from 'react';
import { View, FlatList, TextInput, Button, StyleSheet } from 'react-native';
import { use${name} } from '../../hooks/use${name}';
import { ${name}Card } from '../../components/${name}Card';
import { ${name}SearchCapability } from '../../capabilities/${slug}-search';
import { StyledText } from '../../framework/ui/StyledText';

/**
 * Compositional Screen for ${name} with CRUD, AI Search, and Sync.
 * Auto-generated by Zoe Compositional Blueprint.
 */
export const ${name}CompositionScreen: React.FC = () => {
  const { data, loading, error } = use${name}();
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState<any[]>([]);

  const handleSearch = async () => {
    const response = await ${name}SearchCapability.run({ query: searchQuery });
    if (response.success) {
      setSearchResults(response.result.results);
    }
  };

  if (loading) return <StyledText>Loading...</StyledText>;
  if (error) return <StyledText>Error: {error.message}</StyledText>;

  return (
    <View style={styles.container}>
      <View style={styles.searchSection}>
        <TextInput
          style={styles.input}
          placeholder="Search ${name} with AI..."
          value={searchQuery}
          onChangeText={setSearchQuery}
        />
        <Button title="Search" onPress={handleSearch} />
      </View>
      
      <FlatList
        data={searchResults.length > 0 ? searchResults : data}
        keyExtractor={(item) => item.identifier || item.id}
        renderItem={({ item }) => <${name}Card data={item} />}
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16 },
  searchSection: { flexDirection: 'row', marginBottom: 16 },
  input: { flex: 1, borderWidth: 1, borderColor: '#ccc', marginRight: 8, padding: 8, borderRadius: 4 },
});
`;

  return {
    semanticType,
    hook,
    ui,
    sync,
    aiSearch,
    screen
  };
};
