import { GraphNode } from '../../lib/vkg/types';

/**
 * Represents a W3C RDF / Schema.org CreativeWork semantic entity.
 * Auto-generated by Hygen.
 */
export interface CreativeWork extends GraphNode {
  '@type': 'https://schema.org/CreativeWork';
  name?: string;
  description?: string;
  identifier?: string;
  [property: string]: any;
}
