import { GraphNode } from '../../lib/vkg/types';

/**
 * Represents a W3C RDF / Schema.org Sermon semantic entity.
 * Auto-generated by Hygen.
 */
export interface Sermon extends GraphNode {
  '@type': 'https://schema.org/Sermon';
  name?: string;
  description?: string;
  identifier?: string;
  [property: string]: any;
}
