-- Virtual RDF/JSON-LD View mapping relational database tables to Schema.org Event
-- Auto-generated by Hygen.

-- CREATE OR REPLACE VIEW event_ld AS
-- SELECT 
--   id AS "@id",
--   'https://schema.org/Event' AS "@type",
--   name AS "name",
--   description AS "description"
-- FROM your_relational_table;
