-- Virtual RDF/JSON-LD View mapping relational database tables to Schema.org CreativeWork
-- Auto-generated by Hygen.

-- CREATE OR REPLACE VIEW creativework_ld AS
-- SELECT 
--   id AS "@id",
--   'https://schema.org/CreativeWork' AS "@type",
--   name AS "name",
--   description AS "description"
-- FROM your_relational_table;
