-- Virtual RDF/JSON-LD View mapping relational database tables to Schema.org Sermon
-- Auto-generated by Hygen.

-- CREATE OR REPLACE VIEW sermon_ld AS
-- SELECT 
--   id AS "@id",
--   'https://schema.org/Sermon' AS "@type",
--   name AS "name",
--   description AS "description"
-- FROM your_relational_table;
